services:
  - type: web
    name: gemini-sumAI
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
